server:
  internalPort: "5005"
  externalPort: "5005"
  runMode: "debug"
  domain: "localhost"

logger:
  filePath: "../logs/"
  encoding: "json"
  level: "debug"
  logger: "zap"

cors:
  allowOrigins: "*"

postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "admin"
  dbName: "visper_db"
  sslMode: "disable"
  maxIdleConns: 15
  maxOpenConns: 100
  connMaxLifetime: 5s # 5 seconds

redis:
  host: "localhost"
  port: "6379"
  password: "password"
  db: "0"
  dialTimeout: 5s # 5 seconds
  readTimeout: 5s # 5 seconds
  writeTimeout: 5s # 5 seconds
  poolSize: 10
  poolTimeout: 15s # 15 seconds
  idleCheckFrequency: 500ms # 500 milliseconds
